// List of US Cities, States and country names

export const CITY_NAMES = [
  { name: 'Abilene' },
  { name: 'Akron' },
  { name: 'Albuquerque' },
  { name: 'Alexandria' },
  { name: 'Allentown' },
  { name: 'Amarillo' },
  { name: 'Anaheim' },
  { name: 'Anchorage' },
  { name: 'Ann Arbor' },
  { name: 'Antioch' },
  { name: 'Arlington' },
  { name: 'Arvada' },
  { name: 'Athens' },
  { name: 'Atlanta' },
  { name: 'Augusta' },
  { name: 'Aurora' },
  { name: 'Aurora' },
  { name: 'Austin' },
  { name: 'Bakersfield' },
  { name: 'Baltimore' },
  { name: 'Baton Rouge' },
  { name: 'Beaumont' },
  { name: 'Bellevue' },
  { name: 'Berkeley' },
  { name: 'Billings' },
  { name: 'Birmingham' },
  { name: 'Boise' },
  { name: 'Boston' },
  { name: 'Boulder' },
  { name: 'Bridgeport' },
  { name: 'Broken Arrow' },
  { name: 'Brownsville' },
  { name: 'Buffalo' },
  { name: 'Burbank' },
  { name: 'Cambridge' },
  { name: 'Cape Coral' },
  { name: 'Carlsbad' },
  { name: 'Carrollton' },
  { name: 'Cary' },
  { name: 'Cedar Rapids' },
  { name: 'Centennial' },
  { name: 'Chandler' },
  { name: 'Charleston' },
  { name: 'Charlotte' },
  { name: 'Chattanooga' },
  { name: 'Chesapeake' },
  { name: 'Chicago' },
  { name: 'Chula Vista' },
  { name: 'Cincinnati' },
  { name: 'Clarksville' },
  { name: 'Clearwater' },
  { name: 'Cleveland' },
  { name: 'Clinton' },
  { name: 'Clovis' },
  { name: 'College Station' },
  { name: 'Colorado Springs' },
  { name: 'Columbia' },
  { name: 'Columbia' },
  { name: 'Columbus' },
  { name: 'Columbus' },
  { name: 'Concord' },
  { name: 'Coral Springs' },
  { name: 'Corona' },
  { name: 'Corpus Christi' },
  { name: 'Costa Mesa' },
  { name: 'Dallas' },
  { name: 'Daly City' },
  { name: 'Davenport' },
  { name: 'Davie' },
  { name: 'Dayton' },
  { name: 'Denton' },
  { name: 'Denver' },
  { name: 'Des Moines' },
  { name: 'Detroit' },
  { name: 'Downey' },
  { name: 'Durham' },
  { name: 'Edison' },
  { name: 'El Cajon' },
  { name: 'El Monte' },
  { name: 'El Paso' },
  { name: 'Elgin' },
  { name: 'Elizabeth' },
  { name: 'Elk Grove' },
  { name: 'Escondido' },
  { name: 'Eugene' },
  { name: 'Evansville' },
  { name: 'Everett' },
  { name: 'Fairfield' },
  { name: 'Fargo' },
  { name: 'Fayetteville' },
  { name: 'Fontana' },
  { name: 'Fort Collins' },
  { name: 'Fort Lauderdale' },
  { name: 'Fort Wayne' },
  { name: 'Fort Worth' },
  { name: 'Fremont' },
  { name: 'Fresno' },
  { name: 'Frisco' },
  { name: 'Fullerton' },
  { name: 'Gainesville' },
  { name: 'Garden Grove' },
  { name: 'Garland' },
  { name: 'Gilbert' },
  { name: 'Glendale' },
  { name: 'Glendale' },
  { name: 'Grand Prairie' },
  { name: 'Grand Rapids' },
  { name: 'Greeley' },
  { name: 'Green Bay' },
  { name: 'Greensboro' },
  { name: 'Gresham' },
  { name: 'Hampton' },
  { name: 'Hartford' },
  { name: 'Hayward' },
  { name: 'Henderson' },
  { name: 'Hialeah' },
  { name: 'High Point' },
  { name: 'Hillsboro' },
  { name: 'Hollywood' },
  { name: 'Honolulu' },
  { name: 'Houston' },
  { name: 'Huntington Beach' },
  { name: 'Huntsville' },
  { name: 'Independence' },
  { name: 'Indianapolis' },
  { name: 'Inglewood' },
  { name: 'Irvine' },
  { name: 'Irving' },
  { name: 'Jackson' },
  { name: 'Jacksonville' },
  { name: 'Jersey City' },
  { name: 'Joliet' },
  { name: 'Jurupa Valley' },
  { name: 'Kansas City' },
  { name: 'Kansas City' },
  { name: 'Kent' },
  { name: 'Killeen' },
  { name: 'Knoxville' },
  { name: 'Lafayette' },
  { name: 'Lakeland' },
  { name: 'Lakewood' },
  { name: 'Lakewood' },
  { name: 'Lancaster' },
  { name: 'Lansing' },
  { name: 'Laredo' },
  { name: 'Las Cruces' },
  { name: 'Las Vegas' },
  { name: 'League City' },
  { name: 'Lewisville' },
  { name: 'Lexington' },
  { name: 'Lincoln' },
  { name: 'Little Rock' },
  { name: 'Long Beach' },
  { name: 'Los Angeles' },
  { name: 'Louisville' },
  { name: 'Lowell' },
  { name: 'Lubbock' },
  { name: 'Macon' },
  { name: 'Madison' },
  { name: 'Manchester' },
  { name: 'McAllen' },
  { name: 'McKinney' },
  { name: 'Memphis' },
  { name: 'Mesa' },
  { name: 'Mesquite' },
  { name: 'Miami Gardens' },
  { name: 'Miami' },
  { name: 'Midland' },
  { name: 'Milwaukee' },
  { name: 'Minneapolis' },
  { name: 'Miramar' },
  { name: 'Mobile' },
  { name: 'Modesto' },
  { name: 'Montgomery' },
  { name: 'Moreno Valley' },
  { name: 'Murfreesboro' },
  { name: 'Murrieta' },
  { name: 'Naperville' },
  { name: 'Nashville' },
  { name: 'New Haven' },
  { name: 'New Orleans' },
  { name: 'New York' },
  { name: 'Newark' },
  { name: 'Newport News' },
  { name: 'Norfolk' },
  { name: 'Norman' },
  { name: 'North Charleston' },
  { name: 'North Las Vegas' },
  { name: 'Norwalk' },
  { name: 'Oakland' },
  { name: 'Oceanside' },
  { name: 'Odessa' },
  { name: 'Oklahoma City' },
  { name: 'Olathe' },
  { name: 'Omaha' },
  { name: 'Ontario' },
  { name: 'Orange' },
  { name: 'Orlando' },
  { name: 'Overland Park' },
  { name: 'Oxnard' },
  { name: 'Palm Bay' },
  { name: 'Palmdale' },
  { name: 'Pasadena' },
  { name: 'Pasadena' },
  { name: 'Paterson' },
  { name: 'Pearland' },
  { name: 'Pembroke Pines' },
  { name: 'Peoria' },
  { name: 'Peoria' },
  { name: 'Philadelphia' },
  { name: 'Phoenix' },
  { name: 'Pittsburgh' },
  { name: 'Plano' },
  { name: 'Pomona' },
  { name: 'Pompano Beach' },
  { name: 'Port St. Lucie' },
  { name: 'Portland' },
  { name: 'Providence' },
  { name: 'Provo' },
  { name: 'Pueblo' },
  { name: 'Raleigh' },
  { name: 'Rancho Cucamonga' },
  { name: 'Reno' },
  { name: 'Renton' },
  { name: 'Rialto' },
  { name: 'Richardson' },
  { name: 'Richmond' },
  { name: 'Richmond' },
  { name: 'Riverside' },
  { name: 'Rochester' },
  { name: 'Rochester' },
  { name: 'Rockford' },
  { name: 'Roseville' },
  { name: 'Round Rock' },
  { name: 'Sacramento' },
  { name: 'Saint Paul' },
  { name: 'Salem' },
  { name: 'Salinas' },
  { name: 'Salt Lake City' },
  { name: 'San Angelo' },
  { name: 'San Antonio' },
  { name: 'San Bernardino' },
  { name: 'San Diego' },
  { name: 'San Francisco' },
  { name: 'San Jose' },
  { name: 'San Mateo' },
  { name: 'Sandy Springs' },
  { name: 'Santa Ana' },
  { name: 'Santa Clara' },
  { name: 'Santa Clarita' },
  { name: 'Santa Maria' },
  { name: 'Santa Rosa' },
  { name: 'Savannah' },
  { name: 'Scottsdale' },
  { name: 'Seattle' },
  { name: 'Shreveport' },
  { name: 'Simi Valley' },
  { name: 'Sioux Falls' },
  { name: 'South Bend' },
  { name: 'Spokane' },
  { name: 'Springfield' },
  { name: 'Springfield' },
  { name: 'Springfield' },
  { name: 'St. Louis' },
  { name: 'St. Petersburg' },
  { name: 'Stamford' },
  { name: 'Sterling Heights' },
  { name: 'Stockton' },
  { name: 'Sunnyvale' },
  { name: 'Surprise' },
  { name: 'Syracuse' },
  { name: 'Tacoma' },
  { name: 'Tallahassee' },
  { name: 'Tampa' },
  { name: 'Temecula' },
  { name: 'Tempe' },
  { name: 'Thornton' },
  { name: 'Thousand Oaks' },
  { name: 'Toledo' },
  { name: 'Topeka' },
  { name: 'Torrance' },
  { name: 'Tucson' },
  { name: 'Tulsa' },
  { name: 'Tyler' },
  { name: 'Vallejo' },
  { name: 'Vancouver' },
  { name: 'Ventura' },
  { name: 'Victorville' },
  { name: 'Virginia Beach' },
  { name: 'Visalia' },
  { name: 'Vista' },
  { name: 'Waco' },
  { name: 'Warren' },
  { name: 'Washington' },
  { name: 'Waterbury' },
  { name: 'West Covina' },
  { name: 'West Jordan' },
  { name: 'West Palm Beach' },
  { name: 'West Valley City' },
  { name: 'Westminster' },
  { name: 'Wichita Falls' },
  { name: 'Wichita' },
  { name: 'Wilmington' },
  { name: 'Winston–Salem' },
  { name: 'Woodbridge' },
  { name: 'Worcester' },
  { name: 'Yonkers' },
]

export const STATE_NAMES = [
  { name: 'Alabama', abbreviation: 'AL' },
  { name: 'Alaska', abbreviation: 'AK' },
  { name: 'American Samoa', abbreviation: 'AS' },
  { name: 'Arizona', abbreviation: 'AZ' },
  { name: 'Arkansas', abbreviation: 'AR' },
  { name: 'California', abbreviation: 'CA' },
  { name: 'Colorado', abbreviation: 'CO' },
  { name: 'Connecticut', abbreviation: 'CT' },
  { name: 'Delaware', abbreviation: 'DE' },
  { name: 'District Of Columbia', abbreviation: 'DC' },
  { name: 'Federated States Of Micronesia', abbreviation: 'FM' },
  { name: 'Florida', abbreviation: 'FL' },
  { name: 'Georgia', abbreviation: 'GA' },
  { name: 'Guam', abbreviation: 'GU' },
  { name: 'Hawaii', abbreviation: 'HI' },
  { name: 'Idaho', abbreviation: 'ID' },
  { name: 'Illinois', abbreviation: 'IL' },
  { name: 'Indiana', abbreviation: 'IN' },
  { name: 'Iowa', abbreviation: 'IA' },
  { name: 'Kansas', abbreviation: 'KS' },
  { name: 'Kentucky', abbreviation: 'KY' },
  { name: 'Louisiana', abbreviation: 'LA' },
  { name: 'Maine', abbreviation: 'ME' },
  { name: 'Marshall Islands', abbreviation: 'MH' },
  { name: 'Maryland', abbreviation: 'MD' },
  { name: 'Massachusetts', abbreviation: 'MA' },
  { name: 'Michigan', abbreviation: 'MI' },
  { name: 'Minnesota', abbreviation: 'MN' },
  { name: 'Mississippi', abbreviation: 'MS' },
  { name: 'Missouri', abbreviation: 'MO' },
  { name: 'Montana', abbreviation: 'MT' },
  { name: 'Nebraska', abbreviation: 'NE' },
  { name: 'Nevada', abbreviation: 'NV' },
  { name: 'New Hampshire', abbreviation: 'NH' },
  { name: 'New Jersey', abbreviation: 'NJ' },
  { name: 'New Mexico', abbreviation: 'NM' },
  { name: 'New York', abbreviation: 'NY' },
  { name: 'North Carolina', abbreviation: 'NC' },
  { name: 'North Dakota', abbreviation: 'ND' },
  { name: 'Northern Mariana Islands', abbreviation: 'MP' },
  { name: 'Ohio', abbreviation: 'OH' },
  { name: 'Oklahoma', abbreviation: 'OK' },
  { name: 'Oregon', abbreviation: 'OR' },
  { name: 'Palau', abbreviation: 'PW' },
  { name: 'Pennsylvania', abbreviation: 'PA' },
  { name: 'Puerto Rico', abbreviation: 'PR' },
  { name: 'Rhode Island', abbreviation: 'RI' },
  { name: 'South Carolina', abbreviation: 'SC' },
  { name: 'South Dakota', abbreviation: 'SD' },
  { name: 'Tennessee', abbreviation: 'TN' },
  { name: 'Texas', abbreviation: 'TX' },
  { name: 'Utah', abbreviation: 'UT' },
  { name: 'Vermont', abbreviation: 'VT' },
  { name: 'Virgin Islands', abbreviation: 'VI' },
  { name: 'Virginia', abbreviation: 'VA' },
  { name: 'Washington', abbreviation: 'WA' },
  { name: 'West Virginia', abbreviation: 'WV' },
  { name: 'Wisconsin', abbreviation: 'WI' },
  { name: 'Wyoming', abbreviation: 'WY' },
]

export const COUNTRY_NAMES = [
  { name: 'Afghanistan', code: 'AF' },
  { name: 'Aland Islands', code: 'AX' },
  { name: 'Albania', code: 'AL' },
  { name: 'Algeria', code: 'DZ' },
  { name: 'American Samoa', code: 'AS' },
  { name: 'Andorra', code: 'AD' },
  { name: 'Angola', code: 'AO' },
  { name: 'Anguilla', code: 'AI' },
  { name: 'Antarctica', code: 'AQ' },
  { name: 'Antigua and Barbuda', code: 'AG' },
  { name: 'Argentina', code: 'AR' },
  { name: 'Armenia', code: 'AM' },
  { name: 'Aruba', code: 'AW' },
  { name: 'Australia', code: 'AU' },
  { name: 'Austria', code: 'AT' },
  { name: 'Azerbaijan', code: 'AZ' },
  { name: 'Bahamas', code: 'BS' },
  { name: 'Bahrain', code: 'BH' },
  { name: 'Bangladesh', code: 'BD' },
  { name: 'Barbados', code: 'BB' },
  { name: 'Belarus', code: 'BY' },
  { name: 'Belgium', code: 'BE' },
  { name: 'Belize', code: 'BZ' },
  { name: 'Benin', code: 'BJ' },
  { name: 'Bermuda', code: 'BM' },
  { name: 'Bhutan', code: 'BT' },
  { name: 'Bolivia', code: 'BO' },
  { name: 'Bosnia and Herzegovina', code: 'BA' },
  { name: 'Botswana', code: 'BW' },
  { name: 'Bouvet Island', code: 'BV' },
  { name: 'Brazil', code: 'BR' },
  { name: 'British Indian Ocean Territory', code: 'IO' },
  { name: 'Brunei Darussalam', code: 'BN' },
  { name: 'Bulgaria', code: 'BG' },
  { name: 'Burkina Faso', code: 'BF' },
  { name: 'Burundi', code: 'BI' },
  { name: 'Cambodia', code: 'KH' },
  { name: 'Cameroon', code: 'CM' },
  { name: 'Canada', code: 'CA' },
  { name: 'Cape Verde', code: 'CV' },
  { name: 'Cayman Islands', code: 'KY' },
  { name: 'Central African Republic', code: 'CF' },
  { name: 'Chad', code: 'TD' },
  { name: 'Chile', code: 'CL' },
  { name: 'China', code: 'CN' },
  { name: 'Christmas Island', code: 'CX' },
  { name: 'Cocos (Keeling) Islands', code: 'CC' },
  { name: 'Colombia', code: 'CO' },
  { name: 'Comoros', code: 'KM' },
  { name: 'Congo', code: 'CG' },
  { name: 'Congo, The Democratic Republic of the', code: 'CD' },
  { name: 'Cook Islands', code: 'CK' },
  { name: 'Costa Rica', code: 'CR' },
  { name: "Cote D'Ivoire", code: 'CI' },
  { name: 'Croatia', code: 'HR' },
  { name: 'Cuba', code: 'CU' },
  { name: 'Cyprus', code: 'CY' },
  { name: 'Czech Republic', code: 'CZ' },
  { name: 'Denmark', code: 'DK' },
  { name: 'Djibouti', code: 'DJ' },
  { name: 'Dominica', code: 'DM' },
  { name: 'Dominican Republic', code: 'DO' },
  { name: 'Ecuador', code: 'EC' },
  { name: 'Egypt', code: 'EG' },
  { name: 'El Salvador', code: 'SV' },
  { name: 'Equatorial Guinea', code: 'GQ' },
  { name: 'Eritrea', code: 'ER' },
  { name: 'Estonia', code: 'EE' },
  { name: 'Ethiopia', code: 'ET' },
  { name: 'Falkland Islands (Malvinas)', code: 'FK' },
  { name: 'Faroe Islands', code: 'FO' },
  { name: 'Fiji', code: 'FJ' },
  { name: 'Finland', code: 'FI' },
  { name: 'France', code: 'FR' },
  { name: 'French Guiana', code: 'GF' },
  { name: 'French Polynesia', code: 'PF' },
  { name: 'French Southern Territories', code: 'TF' },
  { name: 'Gabon', code: 'GA' },
  { name: 'Gambia', code: 'GM' },
  { name: 'Georgia', code: 'GE' },
  { name: 'Germany', code: 'DE' },
  { name: 'Ghana', code: 'GH' },
  { name: 'Gibraltar', code: 'GI' },
  { name: 'Greece', code: 'GR' },
  { name: 'Greenland', code: 'GL' },
  { name: 'Grenada', code: 'GD' },
  { name: 'Guadeloupe', code: 'GP' },
  { name: 'Guam', code: 'GU' },
  { name: 'Guatemala', code: 'GT' },
  { name: 'Guernsey', code: 'GG' },
  { name: 'Guinea', code: 'GN' },
  { name: 'Guinea-Bissau', code: 'GW' },
  { name: 'Guyana', code: 'GY' },
  { name: 'Haiti', code: 'HT' },
  { name: 'Heard Island and Mcdonald Islands', code: 'HM' },
  { name: 'Holy See (Vatican City State)', code: 'VA' },
  { name: 'Honduras', code: 'HN' },
  { name: 'Hong Kong', code: 'HK' },
  { name: 'Hungary', code: 'HU' },
  { name: 'Iceland', code: 'IS' },
  { name: 'India', code: 'IN' },
  { name: 'Indonesia', code: 'ID' },
  { name: 'Iran, Islamic Republic Of', code: 'IR' },
  { name: 'Iraq', code: 'IQ' },
  { name: 'Ireland', code: 'IE' },
  { name: 'Isle of Man', code: 'IM' },
  { name: 'Israel', code: 'IL' },
  { name: 'Italy', code: 'IT' },
  { name: 'Jamaica', code: 'JM' },
  { name: 'Japan', code: 'JP' },
  { name: 'Jersey', code: 'JE' },
  { name: 'Jordan', code: 'JO' },
  { name: 'Kazakhstan', code: 'KZ' },
  { name: 'Kenya', code: 'KE' },
  { name: 'Kiribati', code: 'KI' },
  { name: "Democratic People's Republic of Korea", code: 'KP' },
  { name: 'Korea, Republic of', code: 'KR' },
  { name: 'Kosovo', code: 'XK' },
  { name: 'Kuwait', code: 'KW' },
  { name: 'Kyrgyzstan', code: 'KG' },
  { name: "Lao People's Democratic Republic", code: 'LA' },
  { name: 'Latvia', code: 'LV' },
  { name: 'Lebanon', code: 'LB' },
  { name: 'Lesotho', code: 'LS' },
  { name: 'Liberia', code: 'LR' },
  { name: 'Libyan Arab Jamahiriya', code: 'LY' },
  { name: 'Liechtenstein', code: 'LI' },
  { name: 'Lithuania', code: 'LT' },
  { name: 'Luxembourg', code: 'LU' },
  { name: 'Macao', code: 'MO' },
  { name: 'Macedonia, The Former Yugoslav Republic of', code: 'MK' },
  { name: 'Madagascar', code: 'MG' },
  { name: 'Malawi', code: 'MW' },
  { name: 'Malaysia', code: 'MY' },
  { name: 'Maldives', code: 'MV' },
  { name: 'Mali', code: 'ML' },
  { name: 'Malta', code: 'MT' },
  { name: 'Marshall Islands', code: 'MH' },
  { name: 'Martinique', code: 'MQ' },
  { name: 'Mauritania', code: 'MR' },
  { name: 'Mauritius', code: 'MU' },
  { name: 'Mayotte', code: 'YT' },
  { name: 'Mexico', code: 'MX' },
  { name: 'Micronesia, Federated States of', code: 'FM' },
  { name: 'Moldova, Republic of', code: 'MD' },
  { name: 'Monaco', code: 'MC' },
  { name: 'Mongolia', code: 'MN' },
  { name: 'Montenegro', code: 'ME' },
  { name: 'Montserrat', code: 'MS' },
  { name: 'Morocco', code: 'MA' },
  { name: 'Mozambique', code: 'MZ' },
  { name: 'Myanmar', code: 'MM' },
  { name: 'Namibia', code: 'NA' },
  { name: 'Nauru', code: 'NR' },
  { name: 'Nepal', code: 'NP' },
  { name: 'Netherlands', code: 'NL' },
  { name: 'Netherlands Antilles', code: 'AN' },
  { name: 'New Caledonia', code: 'NC' },
  { name: 'New Zealand', code: 'NZ' },
  { name: 'Nicaragua', code: 'NI' },
  { name: 'Niger', code: 'NE' },
  { name: 'Nigeria', code: 'NG' },
  { name: 'Niue', code: 'NU' },
  { name: 'Norfolk Island', code: 'NF' },
  { name: 'Northern Mariana Islands', code: 'MP' },
  { name: 'Norway', code: 'NO' },
  { name: 'Oman', code: 'OM' },
  { name: 'Pakistan', code: 'PK' },
  { name: 'Palau', code: 'PW' },
  { name: 'Palestinian Territory, Occupied', code: 'PS' },
  { name: 'Panama', code: 'PA' },
  { name: 'Papua New Guinea', code: 'PG' },
  { name: 'Paraguay', code: 'PY' },
  { name: 'Peru', code: 'PE' },
  { name: 'Philippines', code: 'PH' },
  { name: 'Pitcairn', code: 'PN' },
  { name: 'Poland', code: 'PL' },
  { name: 'Portugal', code: 'PT' },
  { name: 'Puerto Rico', code: 'PR' },
  { name: 'Qatar', code: 'QA' },
  { name: 'Reunion', code: 'RE' },
  { name: 'Romania', code: 'RO' },
  { name: 'Russian Federation', code: 'RU' },
  { name: 'Rwanda', code: 'RW' },
  { name: 'Saint Helena', code: 'SH' },
  { name: 'Saint Kitts and Nevis', code: 'KN' },
  { name: 'Saint Lucia', code: 'LC' },
  { name: 'Saint Pierre and Miquelon', code: 'PM' },
  { name: 'Saint Vincent and the Grenadines', code: 'VC' },
  { name: 'Samoa', code: 'WS' },
  { name: 'San Marino', code: 'SM' },
  { name: 'Sao Tome and Principe', code: 'ST' },
  { name: 'Saudi Arabia', code: 'SA' },
  { name: 'Senegal', code: 'SN' },
  { name: 'Serbia', code: 'RS' },
  { name: 'Seychelles', code: 'SC' },
  { name: 'Sierra Leone', code: 'SL' },
  { name: 'Singapore', code: 'SG' },
  { name: 'Slovakia', code: 'SK' },
  { name: 'Slovenia', code: 'SI' },
  { name: 'Solomon Islands', code: 'SB' },
  { name: 'Somalia', code: 'SO' },
  { name: 'South Africa', code: 'ZA' },
  { name: 'South Georgia and the South Sandwich Islands', code: 'GS' },
  { name: 'Spain', code: 'ES' },
  { name: 'Sri Lanka', code: 'LK' },
  { name: 'Sudan', code: 'SD' },
  { name: 'Suriname', code: 'SR' },
  { name: 'Svalbard and Jan Mayen', code: 'SJ' },
  { name: 'Swaziland', code: 'SZ' },
  { name: 'Sweden', code: 'SE' },
  { name: 'Switzerland', code: 'CH' },
  { name: 'Syrian Arab Republic', code: 'SY' },
  { name: 'Taiwan', code: 'TW' },
  { name: 'Tajikistan', code: 'TJ' },
  { name: 'Tanzania, United Republic of', code: 'TZ' },
  { name: 'Thailand', code: 'TH' },
  { name: 'Timor-Leste', code: 'TL' },
  { name: 'Togo', code: 'TG' },
  { name: 'Tokelau', code: 'TK' },
  { name: 'Tonga', code: 'TO' },
  { name: 'Trinidad and Tobago', code: 'TT' },
  { name: 'Tunisia', code: 'TN' },
  { name: 'Turkey', code: 'TR' },
  { name: 'Turkmenistan', code: 'TM' },
  { name: 'Turks and Caicos Islands', code: 'TC' },
  { name: 'Tuvalu', code: 'TV' },
  { name: 'Uganda', code: 'UG' },
  { name: 'Ukraine', code: 'UA' },
  { name: 'United Arab Emirates', code: 'AE' },
  { name: 'United Kingdom', code: 'GB' },
  { name: 'United States', code: 'US' },
  { name: 'United States Minor Outlying Islands', code: 'UM' },
  { name: 'Uruguay', code: 'UY' },
  { name: 'Uzbekistan', code: 'UZ' },
  { name: 'Vanuatu', code: 'VU' },
  { name: 'Venezuela', code: 'VE' },
  { name: 'Viet Nam', code: 'VN' },
  { name: 'Virgin Islands, British', code: 'VG' },
  { name: 'Virgin Islands, U.S.', code: 'VI' },
  { name: 'Wallis and Futuna', code: 'WF' },
  { name: 'Western Sahara', code: 'EH' },
  { name: 'Yemen', code: 'YE' },
  { name: 'Zambia', code: 'ZM' },
  { name: 'Zimbabwe', code: 'ZW' },
]

export const PHONE_CODES = [
  { code: 'CA', value: '1', name: 'Canada (+1)' },
  { code: 'US', value: '1', name: 'USA (+1)' },
  { code: 'GB', value: '44', name: 'UK (+44)' },
  { code: 'DZ', value: '213', name: 'Algeria (+213)' },
  { code: 'AD', value: '376', name: 'Andorra (+376)' },
  { code: 'AO', value: '244', name: 'Angola (+244)' },
  { code: 'AI', value: '1264', name: 'Anguilla (+1264)' },
  { code: 'AG', value: '1268', name: 'Antigua & Barbuda (+1268)' },
  { code: 'AR', value: '54', name: 'Argentina (+54)' },
  { code: 'AM', value: '374', name: 'Armenia (+374)' },
  { code: 'AW', value: '297', name: 'Aruba (+297)' },
  { code: 'AU', value: '61', name: 'Australia (+61)' },
  { code: 'AT', value: '43', name: 'Austria (+43)' },
  { code: 'AZ', value: '994', name: 'Azerbaijan (+994)' },
  { code: 'BS', value: '1242', name: 'Bahamas (+1242)' },
  { code: 'BH', value: '973', name: 'Bahrain (+973)' },
  { code: 'BD', value: '880', name: 'Bangladesh (+880)' },
  { code: 'BB', value: '1246', name: 'Barbados (+1246)' },
  { code: 'BY', value: '375', name: 'Belarus (+375)' },
  { code: 'BE', value: '32', name: 'Belgium (+32)' },
  { code: 'BZ', value: '501', name: 'Belize (+501)' },
  { code: 'BJ', value: '229', name: 'Benin (+229)' },
  { code: 'BM', value: '1441', name: 'Bermuda (+1441)' },
  { code: 'BT', value: '975', name: 'Bhutan (+975)' },
  { code: 'BO', value: '591', name: 'Bolivia (+591)' },
  { code: 'BA', value: '387', name: 'Bosnia Herzegovina (+387)' },
  { code: 'BW', value: '267', name: 'Botswana (+267)' },
  { code: 'BR', value: '55', name: 'Brazil (+55)' },
  { code: 'BN', value: '673', name: 'Brunei (+673)' },
  { code: 'BG', value: '359', name: 'Bulgaria (+359)' },
  { code: 'BF', value: '226', name: 'Burkina Faso (+226)' },
  { code: 'BI', value: '257', name: 'Burundi (+257)' },
  { code: 'KH', value: '855', name: 'Cambodia (+855)' },
  { code: 'CM', value: '237', name: 'Cameroon (+237)' },
  { code: 'CV', value: '238', name: 'Cape Verde Islands (+238)' },
  { code: 'KY', value: '1345', name: 'Cayman Islands (+1345)' },
  { code: 'CF', value: '236', name: 'Central African Republic (+236)' },
  { code: 'CL', value: '56', name: 'Chile (+56)' },
  { code: 'CN', value: '86', name: 'China (+86)' },
  { code: 'CO', value: '57', name: 'Colombia (+57)' },
  { code: 'KM', value: '269', name: 'Comoros (+269)' },
  { code: 'CG', value: '242', name: 'Congo (+242)' },
  { code: 'CK', value: '682', name: 'Cook Islands (+682)' },
  { code: 'CR', value: '506', name: 'Costa Rica (+506)' },
  { code: 'HR', value: '385', name: 'Croatia (+385)' },
  { code: 'CU', value: '53', name: 'Cuba (+53)' },
  { code: 'CY', value: '90392', name: 'Cyprus North (+90392)' },
  { code: 'CY', value: '357', name: 'Cyprus South (+357)' },
  { code: 'CZ', value: '42', name: 'Czech Republic (+42)' },
  { code: 'DK', value: '45', name: 'Denmark (+45)' },
  { code: 'DJ', value: '253', name: 'Djibouti (+253)' },
  { code: 'DM', value: '1809', name: 'Dominica (+1809)' },
  { code: 'DO', value: '1809', name: 'Dominican Republic (+1809)' },
  { code: 'EC', value: '593', name: 'Ecuador (+593)' },
  { code: 'EG', value: '20', name: 'Egypt (+20)' },
  { code: 'SV', value: '503', name: 'El Salvador (+503)' },
  { code: 'GQ', value: '240', name: 'Equatorial Guinea (+240)' },
  { code: 'ER', value: '291', name: 'Eritrea (+291)' },
  { code: 'EE', value: '372', name: 'Estonia (+372)' },
  { code: 'ET', value: '251', name: 'Ethiopia (+251)' },
  { code: 'FK', value: '500', name: 'Falkland Islands (+500)' },
  { code: 'FO', value: '298', name: 'Faroe Islands (+298)' },
  { code: 'FJ', value: '679', name: 'Fiji (+679)' },
  { code: 'FI', value: '358', name: 'Finland (+358)' },
  { code: 'FR', value: '33', name: 'France (+33)' },
  { code: 'GF', value: '594', name: 'French Guiana (+594)' },
  { code: 'PF', value: '689', name: 'French Polynesia (+689)' },
  { code: 'GA', value: '241', name: 'Gabon (+241)' },
  { code: 'GM', value: '220', name: 'Gambia (+220)' },
  { code: 'GE', value: '7880', name: 'Georgia (+7880)' },
  { code: 'DE', value: '49', name: 'Germany (+49)' },
  { code: 'GH', value: '233', name: 'Ghana (+233)' },
  { code: 'GI', value: '350', name: 'Gibraltar (+350)' },
  { code: 'GR', value: '30', name: 'Greece (+30)' },
  { code: 'GL', value: '299', name: 'Greenland (+299)' },
  { code: 'GD', value: '1473', name: 'Grenada (+1473)' },
  { code: 'GP', value: '590', name: 'Guadeloupe (+590)' },
  { code: 'GU', value: '671', name: 'Guam (+671)' },
  { code: 'GT', value: '502', name: 'Guatemala (+502)' },
  { code: 'GN', value: '224', name: 'Guinea (+224)' },
  { code: 'GW', value: '245', name: 'Guinea - Bissau (+245)' },
  { code: 'GY', value: '592', name: 'Guyana (+592)' },
  { code: 'HT', value: '509', name: 'Haiti (+509)' },
  { code: 'HN', value: '504', name: 'Honduras (+504)' },
  { code: 'HK', value: '852', name: 'Hong Kong (+852)' },
  { code: 'HU', value: '36', name: 'Hungary (+36)' },
  { code: 'IS', value: '354', name: 'Iceland (+354)' },
  { code: 'IN', value: '91', name: 'India (+91)' },
  { code: 'PK', value: '92', name: 'Pakistan (+92)' },
  { code: 'ID', value: '62', name: 'Indonesia (+62)' },
  { code: 'IR', value: '98', name: 'Iran (+98)' },
  { code: 'IQ', value: '964', name: 'Iraq (+964)' },
  { code: 'IE', value: '353', name: 'Ireland (+353)' },
  { code: 'IL', value: '972', name: 'Israel (+972)' },
  { code: 'IT', value: '39', name: 'Italy (+39)' },
  { code: 'JM', value: '1876', name: 'Jamaica (+1876)' },
  { code: 'JP', value: '81', name: 'Japan (+81)' },
  { code: 'JO', value: '962', name: 'Jordan (+962)' },
  { code: 'KZ', value: '7', name: 'Kazakhstan (+7)' },
  { code: 'KE', value: '254', name: 'Kenya (+254)' },
  { code: 'KI', value: '686', name: 'Kiribati (+686)' },
  { code: 'KP', value: '850', name: 'Korea North (+850)' },
  { code: 'KR', value: '82', name: 'Korea South (+82)' },
  { code: 'KW', value: '965', name: 'Kuwait (+965)' },
  { code: 'KG', value: '996', name: 'Kyrgyzstan (+996)' },
  { code: 'LA', value: '856', name: 'Laos (+856)' },
  { code: 'LV', value: '371', name: 'Latvia (+371)' },
  { code: 'LB', value: '961', name: 'Lebanon (+961)' },
  { code: 'LS', value: '266', name: 'Lesotho (+266)' },
  { code: 'LR', value: '231', name: 'Liberia (+231)' },
  { code: 'LY', value: '218', name: 'Libya (+218)' },
  { code: 'LI', value: '417', name: 'Liechtenstein (+417)' },
  { code: 'LT', value: '370', name: 'Lithuania (+370)' },
  { code: 'LU', value: '352', name: 'Luxembourg (+352)' },
  { code: 'MO', value: '853', name: 'Macao (+853)' },
  { code: 'MK', value: '389', name: 'Macedonia (+389)' },
  { code: 'MG', value: '261', name: 'Madagascar (+261)' },
  { code: 'MW', value: '265', name: 'Malawi (+265)' },
  { code: 'MY', value: '60', name: 'Malaysia (+60)' },
  { code: 'MV', value: '960', name: 'Maldives (+960)' },
  { code: 'ML', value: '223', name: 'Mali (+223)' },
  { code: 'MT', value: '356', name: 'Malta (+356)' },
  { code: 'MH', value: '692', name: 'Marshall Islands (+692)' },
  { code: 'MQ', value: '596', name: 'Martinique (+596)' },
  { code: 'MR', value: '222', name: 'Mauritania (+222)' },
  { code: 'YT', value: '269', name: 'Mayotte (+269)' },
  { code: 'MX', value: '52', name: 'Mexico (+52)' },
  { code: 'FM', value: '691', name: 'Micronesia (+691)' },
  { code: 'MD', value: '373', name: 'Moldova (+373)' },
  { code: 'MC', value: '377', name: 'Monaco (+377)' },
  { code: 'MN', value: '976', name: 'Mongolia (+976)' },
  { code: 'MS', value: '1664', name: 'Montserrat (+1664)' },
  { code: 'MA', value: '212', name: 'Morocco (+212)' },
  { code: 'MZ', value: '258', name: 'Mozambique (+258)' },
  { code: 'MN', value: '95', name: 'Myanmar (+95)' },
  { code: 'NA', value: '264', name: 'Namibia (+264)' },
  { code: 'NR', value: '674', name: 'Nauru (+674)' },
  { code: 'NP', value: '977', name: 'Nepal (+977)' },
  { code: 'NL', value: '31', name: 'Netherlands (+31)' },
  { code: 'NC', value: '687', name: 'New Caledonia (+687)' },
  { code: 'NZ', value: '64', name: 'New Zealand (+64)' },
  { code: 'NI', value: '505', name: 'Nicaragua (+505)' },
  { code: 'NE', value: '227', name: 'Niger (+227)' },
  { code: 'NG', value: '234', name: 'Nigeria (+234)' },
  { code: 'NU', value: '683', name: 'Niue (+683)' },
  { code: 'NF', value: '672', name: 'Norfolk Islands (+672)' },
  { code: 'NP', value: '670', name: 'Northern Marianas (+670)' },
  { code: 'NO', value: '47', name: 'Norway (+47)' },
  { code: 'OM', value: '968', name: 'Oman (+968)' },
  { code: 'PW', value: '680', name: 'Palau (+680)' },
  { code: 'PA', value: '507', name: 'Panama (+507)' },
  { code: 'PG', value: '675', name: 'Papua New Guinea (+675)' },
  { code: 'PY', value: '595', name: 'Paraguay (+595)' },
  { code: 'PE', value: '51', name: 'Peru (+51)' },
  { code: 'PH', value: '63', name: 'Philippines (+63)' },
  { code: 'PL', value: '48', name: 'Poland (+48)' },
  { code: 'PT', value: '351', name: 'Portugal (+351)' },
  { code: 'PR', value: '1787', name: 'Puerto Rico (+1787)' },
  { code: 'QA', value: '974', name: 'Qatar (+974)' },
  { code: 'RE', value: '262', name: 'Reunion (+262)' },
  { code: 'RO', value: '40', name: 'Romania (+40)' },
  { code: 'RU', value: '7', name: 'Russia (+7)' },
  { code: 'RW', value: '250', name: 'Rwanda (+250)' },
  { code: 'SM', value: '378', name: 'San Marino (+378)' },
  { code: 'ST', value: '239', name: 'Sao Tome & Principe (+239)' },
  { code: 'SA', value: '966', name: 'Saudi Arabia (+966)' },
  { code: 'SN', value: '221', name: 'Senegal (+221)' },
  { code: 'CS', value: '381', name: 'Serbia (+381)' },
  { code: 'SC', value: '248', name: 'Seychelles (+248)' },
  { code: 'SL', value: '232', name: 'Sierra Leone (+232)' },
  { code: 'SG', value: '65', name: 'Singapore (+65)' },
  { code: 'SK', value: '421', name: 'Slovak Republic (+421)' },
  { code: 'SI', value: '386', name: 'Slovenia (+386)' },
  { code: 'SB', value: '677', name: 'Solomon Islands (+677)' },
  { code: 'SO', value: '252', name: 'Somalia (+252)' },
  { code: 'ZA', value: '27', name: 'South Africa (+27)' },
  { code: 'ES', value: '34', name: 'Spain (+34)' },
  { code: 'LK', value: '94', name: 'Sri Lanka (+94)' },
  { code: 'SH', value: '290', name: 'St. Helena (+290)' },
  { code: 'KN', value: '1869', name: 'St. Kitts (+1869)' },
  { code: 'SC', value: '1758', name: 'St. Lucia (+1758)' },
  { code: 'SD', value: '249', name: 'Sudan (+249)' },
  { code: 'SR', value: '597', name: 'Suri"name" (+597)' },
  { code: 'SZ', value: '268', name: 'Swaziland (+268)' },
  { code: 'SE', value: '46', name: 'Sweden (+46)' },
  { code: 'CH', value: '41', name: 'Switzerland (+41)' },
  { code: 'SI', value: '963', name: 'Syria (+963)' },
  { code: 'TW', value: '886', name: 'Taiwan (+886)' },
  { code: 'TJ', value: '7', name: 'Tajikstan (+7)' },
  { code: 'TH', value: '66', name: 'Thailand (+66)' },
  { code: 'TG', value: '228', name: 'Togo (+228)' },
  { code: 'TO', value: '676', name: 'Tonga (+676)' },
  { code: 'TT', value: '1868', name: 'Trinidad & Tobago (+1868)' },
  { code: 'TN', value: '216', name: 'Tunisia (+216)' },
  { code: 'TR', value: '90', name: 'Turkey (+90)' },
  { code: 'TM', value: '7', name: 'Turkmenistan (+7)' },
  { code: 'TM', value: '993', name: 'Turkmenistan (+993)' },
  { code: 'TC', value: '1649', name: 'Turks & Caicos Islands (+1649)' },
  { code: 'TV', value: '688', name: 'Tuvalu (+688)' },
  { code: 'UG', value: '256', name: 'Uganda (+256)' },
  { code: 'UA', value: '380', name: 'Ukraine (+380)' },
  { code: 'AE', value: '971', name: 'United Arab Emirates (+971)' },
  { code: 'UY', value: '598', name: 'Uruguay (+598)' },
  { code: 'UZ', value: '7', name: 'Uzbekistan (+7)' },
  { code: 'VU', value: '678', name: 'Vanuatu (+678)' },
  { code: 'VA', value: '379', name: 'Vatican City (+379)' },
  { code: 'VE', value: '58', name: 'Venezuela (+58)' },
  { code: 'VN', value: '84', name: 'Vietnam (+84)' },
  { code: 'VG', value: '84', name: 'Virgin Islands - British (+1284)' },
  { code: 'VI', value: '84', name: 'Virgin Islands - US (+1340)' },
  { code: 'WF', value: '681', name: 'Wallis & Futuna (+681)' },
  { code: 'YE', value: '969', name: 'Yemen (North)(+969)' },
  { code: 'YE', value: '967', name: 'Yemen (South)(+967)' },
  { code: 'ZM', value: '260', name: 'Zambia (+260)' },
  { code: 'ZW', value: '263', name: 'Zimbabwe (+263)' },
]
